version: "3.8"

networks:
  school_net:
    driver: bridge

services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: school-erp
    container_name: erp-app
    ports:
      - 3000:8080
    volumes:
      - ./src:/var/www/html
    networks:
      - school_net