version: "3.8"

networks:
  school_net:
    external:
      name: database_net

services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: school-erp
    container_name: erp-app
    volumes:
      - ./InfixEduv6.5.7:/var/www/html
    ports:
      - 3000:3000
    networks:
      - school_net